language: python
python:
  - "2.7"
  - "3.9"
install:
  - pip install flake8 yapf pytest
  - python setup.py install
script:
  - beatdrift-cli --help
  - pytest beatdrift-cli
  - flake8 beatdrift-cli
  - yapf -d -r beatdrift-cli/
